export const API_URL = 'https://avalon-chat-202n-237c5z6xwa-du.a.run.app/v1'; //SERVER URL
export const SIGNUP = '/signup';
export const SIGNUP_EMAIL_DUPULICATED = '/signup/email/duplicated';
export const SIGNUP_PHONE_SEND = '/signup/phonenumber/authenticate/send';
export const SIGNUP_PHONE_CHECK = '/signup/phonenumber/authenticate/check';
export const SIGNUP_USERINFO = '/profiles';
export const ADDFRIEND_PHONENUMBER = '/friends';
export const LOGIN = '/login';
export const FIND_ID = 'login/email';
export const FIND_PASSWORD = '/login/password/reset';
export const GET_PROFILES_LIST = 'profiles';
export const GET_MY_PROFILE = 'profiles/me';
